var structjuce_1_1_open_g_l_context_1_1_native_context_1_1_mouse_forwarding_n_s_open_g_l_view_class =
[
    [ "MouseForwardingNSOpenGLViewClass", "da/dcf/structjuce_1_1_open_g_l_context_1_1_native_context_1_1_mouse_forwarding_n_s_open_g_l_view_class.html#a61bfac30db41b2aa25e7fb360ec7a495", null ]
];