var juce___s_i_m_d_register__test_8cpp =
[
    [ "juce::dsp::SIMDRegister_test_internal::RandomPrimitive< type, typename >", "dd/dea/structjuce_1_1dsp_1_1_s_i_m_d_register__test__internal_1_1_random_primitive.html", null ],
    [ "juce::dsp::SIMDRegister_test_internal::RandomPrimitive< type, typename std::enable_if< std::is_floating_point< type >::value >::type >", "d2/d61/structjuce_1_1dsp_1_1_s_i_m_d_register__test__internal_1_1_random_primitive_3_01type_00_01typena7ab76f5aaddc3b7200b6259acd2f4b84.html", null ],
    [ "juce::dsp::SIMDRegister_test_internal::RandomPrimitive< type, typename std::enable_if< std::is_integral< type >::value >::type >", "df/d9e/structjuce_1_1dsp_1_1_s_i_m_d_register__test__internal_1_1_random_primitive_3_01type_00_01typenafd53f1174747470456d8c26cc1676279.html", null ],
    [ "juce::dsp::SIMDRegister_test_internal::RandomValue< type >", "da/dec/structjuce_1_1dsp_1_1_s_i_m_d_register__test__internal_1_1_random_value.html", null ],
    [ "juce::dsp::SIMDRegister_test_internal::RandomValue< std::complex< type > >", "da/d00/structjuce_1_1dsp_1_1_s_i_m_d_register__test__internal_1_1_random_value_3_01std_1_1complex_3_01type_01_4_01_4.html", null ],
    [ "juce::dsp::SIMDRegister_test_internal::VecFiller< type >", "d2/d01/structjuce_1_1dsp_1_1_s_i_m_d_register__test__internal_1_1_vec_filler.html", null ],
    [ "juce::dsp::SIMDRegister_test_internal::VecFiller< std::complex< type > >", "dc/d86/structjuce_1_1dsp_1_1_s_i_m_d_register__test__internal_1_1_vec_filler_3_01std_1_1complex_3_01type_01_4_01_4.html", null ],
    [ "juce::dsp::SIMDRegister_test_internal::VecFiller< SIMDRegister< type > >", "df/d6e/structjuce_1_1dsp_1_1_s_i_m_d_register__test__internal_1_1_vec_filler_3_01_s_i_m_d_register_3_01type_01_4_01_4.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests", "dd/d8f/classjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests.html", "dd/d8f/classjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests" ],
    [ "juce::dsp::SIMDRegisterUnitTests::Addition", "d0/daf/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_addition.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::Subtraction", "d1/dc8/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_subtraction.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::Multiplication", "d6/d82/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_multiplication.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::BitAND", "d0/db9/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_bit_a_n_d.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::BitOR", "d8/d86/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_bit_o_r.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::BitXOR", "d2/d27/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_bit_x_o_r.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::InitializationTest", "d8/d66/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_initialization_test.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::AccessTest", "de/d1a/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_access_test.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::OperatorTests< Operation >", "d4/d32/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_operator_tests.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::BitOperatorTests< Operation >", "dd/d37/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_bit_operator_tests.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckComparisonOps", "d9/dfc/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_check_comparison_ops.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckMultiplyAdd", "db/d96/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_check_multiply_add.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckMinMax", "dc/d42/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_check_min_max.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckSum", "d4/daf/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_check_sum.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckAbs", "d0/d3c/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_check_abs.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckTruncate", "d5/d26/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_check_truncate.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckBoolEquals", "d9/da3/structjuce_1_1dsp_1_1_s_i_m_d_register_unit_tests_1_1_check_bool_equals.html", null ]
];