var modules =
[
    [ "Porting Guide for New Versions", "d7/d58/group__porting.html", "d7/d58/group__porting" ],
    [ "FLAC C API", "d3/d45/group__flac.html", "d3/d45/group__flac" ],
    [ "Locks", "d6/d5b/group__base_locks.html", "d6/d5b/group__base_locks" ],
    [ "Basic Interfaces", "d5/dbe/group__plugin_base.html", "d5/dbe/group__plugin_base" ],
    [ "Graphical User Interface", "d9/d60/group__plugin_g_u_i.html", "d9/d60/group__plugin_g_u_i" ],
    [ "Plug-in Type used for subCategories", "d3/d70/group__plug_type.html", null ],
    [ "VST 3 Data Types", "d8/d74/group__vst3typedef.html", null ],
    [ "VST busses", "db/d03/group__vst_bus.html", null ],
    [ "Speaker Arrangements", "d8/d7e/group__speaker_arrangements.html", "d8/d7e/group__speaker_arrangements" ],
    [ "juce_core", "d6/d08/group__juce__core.html", "d6/d08/group__juce__core" ],
    [ "juce_product_unlocking", "d2/de9/group__juce__product__unlocking.html", "d2/de9/group__juce__product__unlocking" ],
    [ "juce_audio_formats", "d1/d5d/group__juce__audio__formats.html", "d1/d5d/group__juce__audio__formats" ],
    [ "juce_data_structures", "db/d34/group__juce__data__structures.html", "db/d34/group__juce__data__structures" ],
    [ "juce_audio_devices", "d2/dc5/group__juce__audio__devices.html", "d2/dc5/group__juce__audio__devices" ],
    [ "juce_opengl", "dc/d55/group__juce__opengl.html", "dc/d55/group__juce__opengl" ],
    [ "juce_cryptography", "d8/d37/group__juce__cryptography.html", "d8/d37/group__juce__cryptography" ],
    [ "juce_dsp", "d8/da4/group__juce__dsp.html", "d8/da4/group__juce__dsp" ],
    [ "juce_audio_basics", "d0/d44/group__juce__audio__basics.html", "d0/d44/group__juce__audio__basics" ],
    [ "juce_audio_utils", "dd/ded/group__juce__audio__utils.html", "dd/ded/group__juce__audio__utils" ],
    [ "juce_audio_plugin_client", "df/d6a/group__juce__audio__plugin__client.html", "df/d6a/group__juce__audio__plugin__client" ],
    [ "juce_osc", "d9/d5c/group__juce__osc.html", "d9/d5c/group__juce__osc" ],
    [ "juce_gui_basics", "d6/d5a/group__juce__gui__basics.html", "d6/d5a/group__juce__gui__basics" ],
    [ "juce_audio_processors", "d3/d60/group__juce__audio__processors.html", "d3/d60/group__juce__audio__processors" ],
    [ "juce_analytics", "d0/d1c/group__juce__analytics.html", "d0/d1c/group__juce__analytics" ],
    [ "juce_events", "da/d41/group__juce__events.html", "da/d41/group__juce__events" ],
    [ "juce_box2d", "db/d42/group__juce__box2d.html", "db/d42/group__juce__box2d" ],
    [ "juce_gui_extra", "d0/d2d/group__juce__gui__extra.html", "d0/d2d/group__juce__gui__extra" ],
    [ "juce_graphics", "d4/dbc/group__juce__graphics.html", "d4/dbc/group__juce__graphics" ],
    [ "juce_video", "d4/d76/group__juce__video.html", "d4/d76/group__juce__video" ]
];