var juce__android___open_s_l_8cpp =
[
    [ "juce::PCMDataFormatEx", "de/d3a/structjuce_1_1_p_c_m_data_format_ex.html", "de/d3a/structjuce_1_1_p_c_m_data_format_ex" ],
    [ "juce::IntfIID< SLObjectItf_ >", "d4/d14/structjuce_1_1_intf_i_i_d_3_01_s_l_object_itf___01_4.html", null ],
    [ "juce::IntfIID< SLEngineItf_ >", "d6/d3d/structjuce_1_1_intf_i_i_d_3_01_s_l_engine_itf___01_4.html", null ],
    [ "juce::IntfIID< SLOutputMixItf_ >", "d9/db6/structjuce_1_1_intf_i_i_d_3_01_s_l_output_mix_itf___01_4.html", null ],
    [ "juce::IntfIID< SLPlayItf_ >", "de/d6a/structjuce_1_1_intf_i_i_d_3_01_s_l_play_itf___01_4.html", null ],
    [ "juce::IntfIID< SLRecordItf_ >", "d8/d83/structjuce_1_1_intf_i_i_d_3_01_s_l_record_itf___01_4.html", null ],
    [ "juce::IntfIID< SLAndroidSimpleBufferQueueItf_ >", "db/dd0/structjuce_1_1_intf_i_i_d_3_01_s_l_android_simple_buffer_queue_itf___01_4.html", null ],
    [ "juce::IntfIID< SLAndroidConfigurationItf_ >", "d9/d3d/structjuce_1_1_intf_i_i_d_3_01_s_l_android_configuration_itf___01_4.html", null ],
    [ "juce::SLObjectItfFree", "d6/d9a/structjuce_1_1_s_l_object_itf_free.html", "d6/d9a/structjuce_1_1_s_l_object_itf_free" ],
    [ "juce::SlObjectRef", "d9/d71/classjuce_1_1_sl_object_ref.html", "d9/d71/classjuce_1_1_sl_object_ref" ],
    [ "juce::SlRef< T >", "d1/d05/classjuce_1_1_sl_ref.html", "d1/d05/classjuce_1_1_sl_ref" ],
    [ "juce::BufferHelpers< T >", "d9/d99/structjuce_1_1_buffer_helpers.html", null ],
    [ "juce::BufferHelpers< int16 >", "d2/d02/structjuce_1_1_buffer_helpers_3_01int16_01_4.html", "d2/d02/structjuce_1_1_buffer_helpers_3_01int16_01_4" ],
    [ "juce::BufferHelpers< float >", "d7/d48/structjuce_1_1_buffer_helpers_3_01float_01_4.html", "d7/d48/structjuce_1_1_buffer_helpers_3_01float_01_4" ],
    [ "juce::OpenSLEngineHolder", "d9/df6/structjuce_1_1_open_s_l_engine_holder.html", "d9/df6/structjuce_1_1_open_s_l_engine_holder" ],
    [ "juce::OpenSLAudioIODevice", "da/d35/classjuce_1_1_open_s_l_audio_i_o_device.html", "da/d35/classjuce_1_1_open_s_l_audio_i_o_device" ],
    [ "juce::OpenSLAudioIODevice::OpenSLQueueRunner< T, Child, RunnerObjectType >", "d0/d7d/structjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_queue_runner.html", "d0/d7d/structjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_queue_runner" ],
    [ "juce::OpenSLAudioIODevice::OpenSLQueueRunnerPlayer< T >", "d2/d3f/structjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_queue_runner_player.html", "d2/d3f/structjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_queue_runner_player" ],
    [ "juce::OpenSLAudioIODevice::OpenSLQueueRunnerRecorder< T >", "d7/d0f/structjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_queue_runner_recorder.html", "d7/d0f/structjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_queue_runner_recorder" ],
    [ "juce::OpenSLAudioIODevice::OpenSLSession", "d7/de9/classjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_session.html", "d7/de9/classjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_session" ],
    [ "juce::OpenSLAudioIODevice::OpenSLSessionT< T >", "da/d8a/classjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_session_t.html", "da/d8a/classjuce_1_1_open_s_l_audio_i_o_device_1_1_open_s_l_session_t" ],
    [ "juce::OpenSLAudioDeviceType", "d0/dd0/classjuce_1_1_open_s_l_audio_device_type.html", "d0/dd0/classjuce_1_1_open_s_l_audio_device_type" ],
    [ "juce::SLRealtimeThread", "d4/d7b/classjuce_1_1_s_l_realtime_thread.html", "d4/d7b/classjuce_1_1_s_l_realtime_thread" ],
    [ "JNI_CLASS_MEMBERS", "d4/dc5/juce__android___open_s_l_8cpp.html#a77ce814e6a25d70cf5c85dfc07cfdcbe", null ],
    [ "SL_ANDROID_DATAFORMAT_PCM_EX", "d4/dc5/juce__android___open_s_l_8cpp.html#a62c75ac87fb9f08abca009ef4b4f323b", null ],
    [ "SL_ANDROID_PCM_REPRESENTATION_FLOAT", "d4/dc5/juce__android___open_s_l_8cpp.html#a986940bceb3d481f462897ab0822db51", null ],
    [ "SL_ANDROID_RECORDING_PRESET_UNPROCESSED", "d4/dc5/juce__android___open_s_l_8cpp.html#a5d34e9441a27b05f820667ada1f460a8", null ],
    [ "CreateEngineFunc", "d4/dc5/juce__android___open_s_l_8cpp.html#a873756e93a5ac044c20c50b4979f892a", null ],
    [ "getEngineHolder", "d4/dc5/juce__android___open_s_l_8cpp.html#ad1bde847b223981a447f421522c97ac2", null ],
    [ "isOpenSLAvailable", "d4/dc5/juce__android___open_s_l_8cpp.html#a6f2527702f7e07cc57fd03289008bbfc", null ],
    [ "juce_createRealtimeAudioThread", "d4/dc5/juce__android___open_s_l_8cpp.html#ac646be6c6bd67b10c4c88b0248a5e523", null ]
];