
name: Build README
on:
  push:
    branches:
      - 'main'
  schedule:
  - cron: "30 15 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pepo and submodule
        uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Build Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
            working-directory: 'JUCE/docs/doxygen'
            doxyfile-path: './Doxygen'
      # - name: Install Ruby and bundle
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler: latest
      #     bundler-cache: true
      #     ruby-version: 3.0.4
      # - name: Build doc fragments
      #   run: bundle exec ./build_docs.rb
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public