
name: Build README
on:
  push:
    branches:
      - 'main'
  schedule:
  - cron: "30 15 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and submodule
        uses: actions/checkout@v3
        with: 
          submodules: true
      - name: Update JUCE
        run: |-
          git submodule update --remote --merge
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "Github Actions Cronjob"
          git add JUCE
          git commit --allow-empty -m "Update JUCE submodule"
          git push    
      - name: Setup python
        uses: actions/setup-python@v3
        
      - name: Run process_source_files.py
        run: python JUCE/docs/doxygen/process_source_files.py JUCE/modules build
        
      - name: Build Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
            doxyfile-path: './Doxyfile'
      # - name: Install Ruby and bundle
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler: latest
      #     bundler-cache: true
      #     ruby-version: 3.0.4
      # - name: Build doc fragments
      #   run: bundle exec ./build_docs.rb
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/html